name: Go version action
description: A GitHub Action providing the latest Go version, your projects minimum Go version, and a build matrix to your workflow
branding:
  icon: box
  color: blue
inputs:
  working-directory:
    description: Working directory where your go.mod file is located
    required: false
    default: .
  unstable:
    description: Include unstable versions of Go (beta, release candidates)
    required: false
    default: 'false'
  unsupported:
    description: Include unsupported versions of Go
    required: false
    default: 'true'
  patch-level:
    description: Include the patch levels on the versions (default is major.minor)
    required: false
    default: 'false'
outputs:
  go-mod-version:
    description: The Go version specified by go.mod
  latest:
    description: The latest Go version
  minimal:
    description: The minimal Go version
  matrix:
    description: A (stringified) array of Go versions from the minimal supported version to the latest released version
  module:
    description: The Go module path (as specified by go.mod)
runs:
  using: node16
  main: dist/index.js
