---
on: pull_request
name: GitHub Actions

# Detect if this action is already running, and cancel it.
# This most likely happened because a second push has been made to a branch.
concurrency:
  group: ${{ github.repository_id }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  actionlint:
    name: Actionlint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: reviewdog/action-actionlint@v1
