---
name: Lint
on: pull_request
permissions:
  contents: read

jobs:
  yamllint:
    name: yaml
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run yamllint
        uses: frenck/action-yamllint@v1.5.0
        with:
          strict: true

  markdownlint:
    name: markdown
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v20

  actionlint:
    name: action
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
