---
on: pull_request
name: YAML
permissions:
  contents: read

# Detect if this action is already running, and cancel it.
# This most likely happened because a second push has been made to a branch.
concurrency:
  group: ${{ github.repository_id }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  yaml-cs-fixer:
    name: Yamllint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Run Yamllint
        uses: frenck/action-yamllint@v1.5.0
        with:
          strict: true
